### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by expcat** [dotnet/dotnet-api-docs.zh-cn#12]
The interface(接口) in the namespace is incorrectly translated into "界面" in the Chinese documentation.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 826fae9a-852c-c9f4-1f9f-a5cde0abc792
* Version Independent ID: 7c74352f-3669-d0a5-1ad5-98c6419f9fd6
* Content: [System.Collections Namespace](https://docs.microsoft.com/zh-cn/dotnet/api/system.collections?view=netcore-2.2#interfaces)
* Content Source: [xml/ns-System.Collections.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/ns-System.Collections.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @expcat 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @expcat
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
`Operator` and `explicit interface` are also mistranslated, and they can't be searched in this repo's source file. 
This issue also exists in other repos, at least zh-tw exists.
![default](https://user-images.githubusercontent.com/24759802/50220797-3fcc2300-03ce-11e9-90b7-fecf909c3554.png)

**Comment by CeciAc** [comment]
Hello, @expcat

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @expcat 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/dotnet/api/system.collections?view=netcore-2.2#interfaces

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team

**Comment by expcat** [comment]
In my case, it's still wrong. Is it because there is a cache?
![interface](https://user-images.githubusercontent.com/4289694/51123482-272d1c80-1857-11e9-8bfb-79632b6f9046.png)

**Comment by CeciAc** [comment]
Hi @expcat 
Don't worry, the fix was implemented but it'll take a few days to appear live.

Kind regards,
Microsoft DOCS International Team

**Comment by expcat** [comment]
Thank you.

**Comment by huww98** [comment]
Although the translation in the main display area is fixed. `显式界面实现` in the left navigation section is still wrong. It should be `显式接口实现`
